//
// Created by morgan on 5/1/2022.
//

#ifndef PLATFORMIO_PROGRAM_CAPACITIVETOUCH_ACTIONS_H
#define PLATFORMIO_PROGRAM_CAPACITIVETOUCH_ACTIONS_H

enum class CapacitiveTouch_Actions {
    ACTION_TOUCH_VALIDATED, ACTION_RELEASE_VALIDATED, ACTION_STANDBY

};
#endif //PLATFORMIO_PROGRAM_CAPACITIVETOUCH_ACTIONS_H