//
// Created by morgan on 4/23/2022.
//

#ifndef PLATFORMIO_PROGRAM_LEDCOLOR_HELPER_INTERFACE_H
#define PLATFORMIO_PROGRAM_LEDCOLOR_HELPER_INTERFACE_H

class LedColor_Helper_Interface {

};

#endif //PLATFORMIO_PROGRAM_LEDCOLOR_HELPER_INTERFACE_H